project:
    type: website
    render:
    - "*.qmd"
    - "!templates/"
#    resources:
#      - scripts/

website:
  title: "Math 221 - Calculus I"
  navbar:
    left:
      - text: "Course Notes"
        href: notes/index.qmd
      - text: "Practice Exam Problems"
        href: exam_practice/index.qmd
    right:
      - text: "Questions?"
        href: about.qmd
  sidebar:
    - id: notes
      title: "Course Notes"
      style: "docked"
      contents:
        - text: "Home"
          href: notes/index.qmd
        - section: "Unit 0: Introduction & Review"
          contents:
            - text: "What is Calculus?"
              href: notes/unit0_index.qmd
            - text: "Functions & Their Properties"
              href: notes/unit0_1.qmd
            - text: "Families of Functions"
              # href: notes/unit0_2.qmd
        - section: "Unit 1: Limits & Continuity"
          contents:
            # - text: "Overview"
            #   href: notes/unit1_index.qmd
            # - text: "Definitions & Intuition"
            #   href: notes/unit1_1.qmd
            # - text: "Limit Properties"
            #   href: notes/unit1_2.qmd
            # - text: "Evaluating Limits Using Algebra"
            #   href: notes/unit1_3.qmd
        - section: "Unit 2: The Derivative"
          contents:
          #  - text: "Overview"
          #    href: notes/unit2/index.qmd
        - section: "Unit 3: Computing Derivatives"
          contents:
          #  - text: "Overview"
          #    href: notes/unit3/index.qmd
        - section: "Unit 4: Applications of Derivatives"
          contents:
          #  - text: "Overview"
          #    href: notes/unit4/index.qmd
        - section: "Unit 5: The Definite Integral"
          contents:
            # - text: "Overview"
            #   href: notes/unit5/index.qmd
        - section: "Unit 6: Antiderivatives"
          contents:
            # - text: "Overview"
            #   href: notes/unit6/index.qmd

    - id: practice
      title: "Practice Exam Problems"
      style: "docked"
      contents:
        - text: "Home"
          href: exam_practice/index.qmd
        - section: "By Topic"
          contents:
            - text: "Unit 0: Functions"
              href: exam_practice/unit0_practice.qmd
            - text: "Unit 1: Limits & Continuity"
              href: exam_practice/unit1_practice.qmd
            - text: "The Derivative"
              href: exam_practice/unit2_practice.qmd
            - text: "Computational Rules"
              href: exam_practice/unit3_practice.qmd
            - text: "Applications of Derivatives"
              href: exam_practice/unit4_practice.qmd
            - text: "The Definite Integral"
              href: exam_practice/unit5_practice.qmd
            - text: "Antiderivatives"
              href: exam_practice/unit6_practice.qmd
  drafts:
    - notes/unit0_2.qmd
    - notes/unit1_index.qmd
    - notes/unit1_1.qmd
    - notes/unit1_2.qmd
    - notes/unit1_3.qmd
    - exam_practice/unit0_practice.qmd
    - exam_practice/unit1_practice.qmd
    - exam_practice/unit2_practice.qmd
    - exam_practice/unit3_practice.qmd
    - exam_practice/unit4_practice.qmd
    - exam_practice/unit5_practice.qmd
    - exam_practice/unit6_practice.qmd
  draft-mode: unlinked

format:
  html:
    theme: 
      light: darkly
      dark: flatly
    css: styles.css
    toc: true
    toc-depth: 3
#    include-in-header:
#    - text: |
#        <script type="importmap">
#        {
#          "imports": {
#            "mathjs": "https://cdn.jsdelivr.net/npm/mathjs@13/+esm"
#          }
#        }
#        </script>