---
title: "Modeling with Families of Functions"
sidebar: notes
---
A *mathematical model* is an abstract mathematical representation of some object, idea, or relationship that exists in the real world. Creating a mathematical model usually involves making some simplifying assumptions about whatever it is we are trying to represent. Using data from measurements or other observations, we try to distill the essential properties that we want our model to capture. We use mathematical models to make estimate or predict, weigh and compare decisions, simulate experiments, and try to discover properties that may otherwise be difficult or costly to observe. 

Be careful when drawing conclusions! Always consider the simplifying assumptions that were made when the model was created. Did we ignore anything that may impact our findings? Under what conditions is it reasonable to believe that the assumptions we made are realistic? These are all important things to include when communicating what you have learned in its real world context.      

## What should you know?

The following families of functions are frequently used as the basis for mathematical models. How well do you know them? We will need to be able to:

- Solve equations involving each of these types of functions.
- Recognize properties of the function from its formula.

It is very helpful if you are familiar enough with each of these families of functions to be able to "see" what the graph looks like and sketch it out by hand without relying on a graphing tool.     

#### Linear Functions
Our first question in creating a mathematical model for a relationship is often *is it linear?* Linear models are simple to understand and easy to work with. Our intuition often relies on linear thinking. 

There are two common ways of writing a linear formula:

$$\begin{align}
&f(x)=mx+b & (\text{Slope-Intercept Form}) \\
&f(x)=m(x-x_0)+y_0 & (\text{Point-Slope Form})
\end{align}$$

#### Power Functions
Useful when modeling something that is strictly increasing or decreasing, but not in a linear way. 

The formula is: 
$$f(x)=k x^p$$
where the power, $p$, can be any real number.

#### Absolute Value Function
Useful when you only need the *magnitude* of a value:
$$ f(x)=|x|$$

#### Exponential Functions
We say a quantity is increasing or decreasing *exponentially* when it always changes by the same *factor* over each unit of time.

There are two different ways of writing exponential functions:

$$f(x)=ab^x = a(1+r)^x$$

where $a$ is the initial value, $b$ is the growth factor, and $r$ is the growth rate,

$$f(x)=ae^{rx}$$

where again $r$ is the *continuous* or *relative* growth rate and again $a$ is the initial value.

#### Logarithmic Functions
Logarithms provide the inverse relationship for exponential growth. They are useful because they can convert something changing on an exponential scale to a linear scale.

The formula is:
$$f(x)=\log_b(x)$$
where $b$ is the base of the logarithm. 

Most often, we will use:
$$\begin{align}
&f(x)=\log(x) & (\text{common log, } b=10)\\
&f(x)=\ln(x) & (\text{natural log, } b=e)
\end{align}$$

#### Trigonometric Functions
Frequently used when trying to model quantities that vary periodically. Also useful in problems involving geometry.

The three main trigonometric functions are:

$$f(x) = \sin(x),~ f(x) = \cos(x),~ f(x) = \tan(x)$$

Also useful are the corresponding reciprocal functions:

$$f(x) = \csc(x) = \frac{1}{\sin(x)},~ f(x) = \sec(x) = \frac{1}{\cos(x)},
f(x) = \cot(x) = \frac{1}{\tan(x)}$$

And inverse functions:
$$f(x) = \arcsin(x) = \sin^{-1}(x),
~f(x) = \arccos(x) = \cos^{-1}(x),
~f(x) = \arctan(x) = \tan^{-1}(x)$$

#### Polynomial Functions
We use polynomials to model relationships that have one or more local extrema. 

The two common ways of writing polynomials are:

$$\begin{align}
&f(x)=a_nx^n +a_{n-1}x^{n-1}+\ldots +a_1x + a_0 & (\text{Standard form}) \\[5pt]
&f(x)=a(x-z_1)^{m_1}(x-z_2)^{m_2}\cdot\ldots\cdot(x-z_k)^{m_k}
& (\text{Factored form})
\end{align}$$

In standard form, the $a_k$s are called *coefficients*; $n$ is the *degree* of the polynomial and $a_n$ is referred to as the *leading coefficient*.

In factored form, the $z_k$s are the *zeros* or *roots* of the polynomial and the $m_k$s are their *multiplicities*; $a$ is the leading coefficient.  

#### Rational Functions
Rational functions are useful when the relationship has *asymptotic behavior*. There are two kinds of asymptotes:

- *vertical* asymptotes: the magnitude of the output value increases without bound near a particular input value
- *horizontal* asymptotes: the output value of the function approaches a specific value as the input tends towards $\pm\infty$.

Rational functions can be written as
$$ f(x)=\frac{p(x)}{q(x)} $$
where $p(x)$ and $q(x)$ are polynomials.

## Problem 1: Population Growth Model

The table below gives the population, measured in **1000s of people**, of three different cities in 2010, 2012, and 2016. The data has been rounded.

| Year | 2010 | 2012 | 2016 |
|:-----|:----:|:----:|:----:|
| City A | 59.8 | 61.8 | 77.8 |
| City B | 60.1 | 68.7 | 85.9 |
| City C | 50.2 | 54.3 | 63.5 |


a. The population of one of these cities is growing linearly and one is growing exponentially. Determine which cities fit each type of growth and find formulas modeling their populations.  
b. The third city's population can be modeled using a function of the form 
$$f(t)=a+kt^p.$$
Find the values of the parameters in this model.
c. Using your models, determine when each city's population will reach 100,000.


## Problem 2: Water Temperature

Emily enjoys swimming at a nearby beach. The temperature of the water throughout the course of the year can be modeled with a sinusoidal function. Currently, the water is 44$^\circ$F, which is the coldest it will be all year. The water will reach its warmest temperature of 80$^\circ$F 180 days from now.

Let $T(x)$ be the sinusoidal function modeling the temperature of the water $x$ days from now.

a. Sketch a graph of $T(x)$. Determine the amplitude, midline, and period.

b. Write a formula for $T(x)$.

c. According to this model, what is the expected temperature of the water 30 days from now?

d. Emily will only go swimming when the temperature of the water is above 74$^\circ$F. How long does Emily have to wait before the water reaches this temperature? (Show all algebraic work.)

**(e)** How many days will the water temperature stay above 74$^\circ$F? Explain your reasoning.


## Problem 3: Polynomials and Rational Functions


a. Let $f(x) = x^4 - 4x^2$. Sketch a graph of $f(x)$. Make sure to show all $x$-intercepts and the end behavior. Use Desmos to check your answer.

b. Let $g(x)$ be the polynomial shown below. Find a formula for $g(x)$ assuming it has the smallest possible degree.

c. Let $f(x)$ and $g(x)$ be the functions from parts (a) and (b). Find all vertical and horizontal asymptotes for the function
$$
h(x) = \frac{g(x)}{f(x)}.
$$
